version: "3"

services:
  php:
    build:
      context: .
    container_name: symfony-php
    volumes:
      - .:/var/www
    ports:
      - "8000:8000"
    environment:
      - APP_ENV=dev
    working_dir: /var/www
